### ISSUE TITLE
Bug mit ET 2.1.0.9002 (per Composer) mit Contao 3.3.7 

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-easy_themes#10]
Hi,

ich habe in eine frische Contao-Installtion ET per Composer eingeladen - nach Aktivierung kommen dv. Fehler zum Vorschein:

1. bei Aktive Module kommen 6 Checkboxen => also nach Seitenlayouts noch eine ohne Beschriftung (im Quelltext steht was von Image-Size...)

2.a) auf der Konsole kommt Fehlermeldung: ```Uncaught ReferenceError: EasyThemes is not defined```

2.b) demzufolge werden die Icons links über Backend-Navigation angezeigt (funktionieren aber) - aber nicht wo sie hin gehören...

**Comment by xantippe** [comment]
Bug 2 hat sich erledingt - lag anscheinend an [contao-bootstrap]
https://community.contao.org/de/showthread.php?54826-Erweiterung-easy_theme-wird-gest%F6rt&p=353676#post353676

"Bug" 1 bleibt...

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-easy_themes/commit/ef145d29107185906181a7a902ecb5aafbb046d7
Kannst du den 2.1.1er-Zweig testen bevor ich ihn veröffentliche, bitte? https://github.com/terminal42/contao-easy_themes/tree/hotfix/2.1.1

**Comment by xantippe** [comment]
kann ich den auch per Composer einspielen?

**Comment by Toflar** [comment]
Ja, `dev-hotfix/2.1.1` installieren.

**Comment by xantippe** [comment]
o.k. gemacht - sieht gut aus: Checkbox ist weg

**Comment by Toflar** [comment]
Danke, Release ist draussen :)

**Comment by xantippe** [comment]
Danke auch!
