### ISSUE TITLE
Easy themes can not be deactivated when be-mod is selected.

### ISSUE THREAD

**Issue by discordier** [terminal42/contao-easy_themes#12]
the check
```php
if ($user->et_enable != 1) {
    return $arrModules;
}
```
is missing in https://github.com/terminal42/contao-easy_themes/blob/master/EasyThemes.php#L242

Therefore as long as there is `be_mod` selected in the database one can not deactivate it.

found by @frontendschlampe

**Comment by Toflar** [comment]
Does the hotfix 2.1.3 branch work for you? /cc @frontendschlampe

**Comment by Schuberth1980** [comment]
Germany text:

Easy_themes wird bei Contao 3.4x leider an der falsche Stelle angezeigt. Nämlich über dem Backend Module Menü, statt unter den Modul Themes.
