### ISSUE TITLE
Add the option to add links to the defined layouts of the selected theme 

### ISSUE THREAD

**Issue by kozi** [terminal42/contao-easy_themes#15]
Add the option to add links to the defined layouts of the selected theme
![layouts](https://cloud.githubusercontent.com/assets/464029/12151568/2c97109e-b4b0-11e5-99f9-d75a52337ea5.png)

**Comment by Toflar** [comment]
I don't think this is the idea behind easy_themes. You can do that with your own extension by modifying the `$GLOBALS['TL_EASY_THEMES_MODULES']` though.
