### ISSUE TITLE
individueller Titel statt automatisch Titel des Themes

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-easy_themes#16]
Wäre es möglich, einen individuellen Titel bei den User-Einstellungen pro Theme anzugeben statt automatisch den Titel des Themes zu benutzen? Wäre oft schon sehr vorteilhaft! Vielleicht auch als Alternative!

**Comment by Toflar** [comment]
Warum individuell pro User? Was soll das bringen? Mich stört eher, dass die Titel zum Teil zu lang sind, aber dann wären sie ja für alle zu lang, insofern kann man's auch gleich im Theme ändern? :-)

**Comment by frontendschlampe** [comment]
naja ... der Titel des Themes ist ja eher ein Name für den "Webworker" - der Titel der Links dann eher für den User - also eine "schöner" Name ;-)

**Comment by Toflar** [comment]
I see, aber warum pro User individuell? Ein "Interner Titel" bei einem Theme wäre ja genug? Das Feld kannst du dann einem normalen User nicht anzeigen. Aber angenommen du und ich arbeiten gemeinsam an einem Theme, warum solltest du es "kurz A" und ich "kurz B" nennen? Ist doch verwirrend? :-)

**Comment by frontendschlampe** [comment]
ja ... natürlich. Da hast du wahr ... ein "interner" Titel ist vollkommen ausreichend

**Comment by Toflar** [comment]
Implementiert im develop-Branch. Zieh's dir mal via Composer rein und sag Bescheid :)

**Comment by frontendschlampe** [comment]
Bescheid ;-) ... geht nicht, da irgendwie das DB-Update fehlt/fehlschlägt ...

`Fatal error: Uncaught exception Exception with message Query error: Unknown column 'easy_themes_internalTitle' in 'field list' (SELECT name,easy_themes_internalTitle FROM tl_theme WHERE id=2) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295`

obwohl ich auf der Seite mit dem DB-Update bin

**Comment by Toflar** [comment]
Ach, die Hooks berücksichtigten den Installprozess mit Composer noch nicht. Magst nochmal mit https://github.com/terminal42/contao-easy_themes/commit/ce5e119a8b24204a3db0358201b8d19966c7c6a3 testen (wieder einfach develop branch)

**Comment by frontendschlampe** [comment]
hab das hier mal auf Contao 3.5.8 probiert und es funzt prima! :-) :+1:

**Comment by Toflar** [comment]
Habe easy_themes 2.2.0 gerade released :)
