### ISSUE TITLE
Add icon in Contao 4.2

### ISSUE THREAD

**Issue by kozi** [terminal42/contao-easy_themes#20]
![unbenannt](https://cloud.githubusercontent.com/assets/464029/16299678/d85bac54-393b-11e6-942f-f39448073e76.PNG)

**Comment by Toflar** [comment]
Contao 4.2 is not supported yet.

**Comment by kozi** [comment]
OK, then i have tested it a little bit and found this little "bug" ;)

**Comment by kozi** [comment]
**^4.0** includes 4.2.

https://semver.mwl.be/#?package=contao%2Fcore-bundle&version=%5E4.0&minimum-stability=stable

**Comment by Toflar** [comment]
The dependency should not allow 4.2 which it currently does. Couldn't know that there will be a new back end theme. But I actually do not care about that. Instead of publishing a bugfix that prevents you from installing it in 4.2 we might as well just add support for it.^^

**Comment by stefansl** [comment]
@kozi there are some more incompatibilities (rightclick, dom-inject, hover-mode) in easy_theme to the new layout. But for now I'm happy, that it's installable and basic working in backend module mode :)

**Comment by rflx** [comment]
+1

**Comment by Toflar** [comment]
Implemented in a4619e38a4be2e1d47002833f24715d1901951e5. Already published as 2.2.3. Enjoy!
