### ISSUE TITLE
Contao 4.2 Modus DOM-Inject Abstand zwischen Icons

### ISSUE THREAD

**Issue by Mynyx** [terminal42/contao-easy_themes#21]
Beim Theme von Contao 4.2 fehlt im Modus DOM-Inject der seitliche Abstand zwischen den Icons.

**Comment by hanski** [comment]
Das betrifft die Kurzansicht und zwar in allen Modi, nicht nur bei DOM-Inject.

**Comment by Toflar** [comment]
Schliesse ich, weil wir nur noch Contao 4.4 supporten werden.
