### ISSUE TITLE
Darstellung bei eingeklappte Layoutmenü

### ISSUE THREAD

**Issue by dackelchen** [terminal42/contao-easy_themes#22]
Moin 
![easy_themes](https://cloud.githubusercontent.com/assets/2857992/19473916/c8109eb0-952d-11e6-9dde-3317796869fc.jpg)

kann es sein, dass sich bei easy.themes ein Fehler eingeschlichen hat?

Wenn ich den Layoutbereich einklappe, sieht zunächst erst mal alles gut aus, Sobald ich aber weiterarbeite und einen beliebigen Menüpunkt in der linken Navigationsleiste anklicke, erscheint das easy_themes-Menü über der Navigation.

Contao 3.5.17 
easy_themes: 2.2.1 (DOM-Inject)

**Comment by Toflar** [comment]
Bitte die neuste Version nutzen für Bugreports.
