### ISSUE TITLE
Darstellungsfehler in Contao 4

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-easy_themes#23]
<img width="298" alt="easy_themes" src="https://cloud.githubusercontent.com/assets/1942550/22399385/8a7537e6-e59b-11e6-90e5-7c7ad6b6816a.png">

`<div class="tl_checkbox_single_container widget">`

Durch das Löschen der CSS-Klasse `tl_checkbox_single_container` wird es richtig angezeigt.

**Comment by aschempp** [comment]
Fixed in 95bde8e13f93709dca8e4bbc9e6259c39efe112e
