### ISSUE TITLE
Contao 4.4 display error - EasyThemes Mode: Back end modules

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-easy_themes#28]
![back-end modules-old](https://user-images.githubusercontent.com/1942550/27436950-17dac92a-5761-11e7-9217-390719806378.png)

- add new Icon: layout (http://feathericons.com/)
- add class="active" to the active list element (li)

![back-end modules-new](https://user-images.githubusercontent.com/1942550/27436961-1dd9d4ba-5761-11e7-945c-e9a34c72b915.png)

**Comment by aschempp** [comment]
Fixed in adacf974ad3a5516ea8908f8cab08211197bce6f and a89b83867dfeefc42c01dc51bdfd93625c3e0d9d
