### ISSUE TITLE
"menatwork/contao-multicolumnwizard" required?

### ISSUE THREAD

**Issue by websolutions-hamburg** [terminal42/contao-easy_themes#30]
Hallo,

ich habe eben den Branch **hotfix/2.2.4** getestet. Kann es sein das die Extension `menatwork/contao-multicolumnwizard` erforderlich ist um die CSS Klasse **version_4-4** nutzen zu können?

So wie ich es im Moment sehe wird diese Klasse nur durch **contao-multicolumnwizard** gesetzt:

```
/* File: MultiColumnWizardHelper.php - Row: 41 */
$objTemplate->ua .= ' version_' . str_replace('.', '-', VERSION) . '-' . str_replace('.', '-', BUILD);
```

**Comment by aschempp** [comment]
Mist, das hab ich wohl übersehen :(

**Comment by aschempp** [comment]
@qzminski can you make a PR with `version_compare` and different stylesheets instead of the class? Also applies to Isotope and maybe Notification Center, please also create a PR there.

**Comment by Toflar** [comment]
Already fixed in hotfix branch.
