### ISSUE TITLE
Bereich offen/geschlossen Status wird nicht gespeichert

### ISSUE THREAD

**Issue by websolutions-hamburg** [terminal42/contao-easy_themes#31]
Wenn man easy_themes als Backend Modul nutzt erscheint ja links im Contao 4.4 Menü ein neuer Bereich. Durch einen Klick auf den Namen des Themes wird dieser Bereich geschlossen oder wieder geöffnet. Der aktuelle Status, ob geschlossener oder geöffneter Bereich, wird jedoch nicht gespeichert. Wenn man die Seite neu lädt, ist der Bereich immer geöffnet.

**Comment by Toflar** [comment]
Hab's grad mit dem aktuellen Hotfix-Branch getestet und das läuft bei mir. Scheint also bereits behoben :-)
