### ISSUE TITLE
Contao 4.4.1 v2.2.3 mode DOM-Inject not visible

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-easy_themes#32]
Wenn **Layout** geöffnet ist, dann ist die ul#easy_themes zwar im DOM vorhanden, aber an der flaschen Stelle
```html
<div id="container" class="cf">
  <ul id="easy_themes" ...
```
anstatt hier
```html
<ul class="tl_level_2">
  <li><a ... >Themes</a>
    <ul id="easy_themes" ...
```
Und sie ist auf display:none. Also unsichtbar. Erst beim Zu- und dann wieder Aufklappen wird sie sichtbar und an die richtige Stelle gebracht.

**Comment by Webstylerin** [comment]
Habe auch ein Problem mit der Darstellung nach dem Update auf die 4.4.1. Nutze easy_themes mit den Einstellungen "DOM-Inject" und Kurzansicht. Bei mir sind die Icons zwar sichtbar, aber ganz oben rechts in der Ecke und nicht mehr an ihrem gewohnten Ort unter "Themes".

![bildschirmfoto 2017-07-13 um 09 54 50](https://user-images.githubusercontent.com/3033160/28156087-817aeb2a-67b1-11e7-8beb-33c2c445d9a9.png)

**Comment by mlwebworker** [comment]
Einzige "vernünftige" Anzeige scheint derzeit "Backendmodul" zu sein

**Comment by Aybee** [comment]
Ist zwar bei euch und auch bei mir falsch, aber warum habt ihr diesen dunkelblauen Hintergrund? Liegt das an eurer Contao Version? Ich habe 4.4.1. Ich sehe diese Icons auch nicht dort, wo ihr sie seht, ich sehe sie überhaupt nicht und mein Hintergrund ist grau.

**Comment by Webstylerin** [comment]
Aybee, keine Ahnung. :) Habe die Seite als 4.4.0 mit dem Contao-Manager aufgesetzt und nun auf 4.4.1 upgedatet. Einstellungen zur Backend-Ansicht habe ich keine geändert, in meinem Benutzer ist das Backend-Theme "flexilbe" eingestellt, habe aber auch keine andere Auswahl.

**Comment by Aybee** [comment]
Seltsam. Habe alles genauso gemacht wie du auch. Nur bei mir ist das grau. In der Online-Demo 4.4.1 auch. Kommt aus der main.css
```css
body {
 background: #eaeaec;
}
```

**Comment by mlwebworker** [comment]
Webstylerin kannst ja jetzt jeden Hauptmenüpunkt den Du nicht immer komplett sehen musst auch einklappen. Dann sieht alles recht aufgeräumt aus.

**Comment by mlwebworker** [comment]
@Aybee Den Teil Links mit den Icons vom DOM-Inject kriegst Du nur zu sehen, wenn Du die Kurzansicht einstellst

**Comment by Aybee** [comment]
Habe ich ja, aber ich sehe da nichts.

**Comment by jscholtysik** [comment]
Ich sehe die Easy Themes Icons auch so wie Webstylerin links oben auf einem dunkelblauen Hintergrund. Contao 4.4.1

**Comment by Aybee** [comment]
Ok, muss ich wohl nicht vestehen.

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-easy_themes/commit/b4b52bbe8be84aee7f1ffd2d0a29c8e5e1721b65
