### ISSUE TITLE
Modus Backend Module - fehlerhafte ".active" Markierung

### ISSUE THREAD

**Issue by websolutions-hamburg** [terminal42/contao-easy_themes#33]
Wenn man den Modus **Backend Module** verwendet und zum Beispiel in den Bereich "Seitenlayouts" aufruft so wird im rechten Menü unter dem Punkt "Layout" der Punkt "Themes" mit der CSS Klasse `.active` markiert und von Easy Themes der Punkt "Seitenlayouts". Soweit so gut.

Wenn man nun aber ein Seitenlayout bearbeitet wird auch der Menüpunkt "Theme bearbeiten" von Easy Theme als aktiv markiert.

Wenn man ein Modul bearbeite ist kein Menüpunkt mehr von Easy Theme als aktiv markiert.

<img width="681" alt="bildschirmfoto" src="https://user-images.githubusercontent.com/26099903/28199613-45bdbc32-6867-11e7-8f52-173a8f30f56d.png">

**Comment by Toflar** [comment]
Fixed/Improved in https://github.com/terminal42/contao-easy_themes/commit/31e6c8022dd3ad04253aa0844ba4f040739e58a0.

**Comment by websolutions-hamburg** [comment]
Der Fehler ist mit Contao 4.4.6 und der Easy Themes Version 2.2.6 wieder da :-(.

Der Menüpunkt `Theme bearbeiten` wird richtig als aktiv markiert dargestellt und bekommt auch die CSS Klasse `.active`. Alle weiteren Menüpunkte wie `Module`oder `Bildgrößen` bekommen die `.active` Klasse nicht und werden somit auch nicht als aktiv markiert dargestellt.

**Comment by Toflar** [comment]
Könnte daran liegen, dass sich das Theme schon wieder geändert hat...

**Comment by Toflar** [comment]
Ich kann das Problem nicht nachstellen. Was genau passt nicht?
