### ISSUE TITLE
No DOM-Inject with Contao 4.4.2, Contao Manager Beta 10 and Easy Themes 2.2.6

### ISSUE THREAD

**Issue by jscholtysik** [terminal42/contao-easy_themes#36]
With Contao 4.4.2 there is no more DOM-Inject. I can activate Easy Themes 2.2.6 in the user settings, but the theme with its submenu is not visible anymore.

There was no problem with Contao 4.4.1 and Easy Themes 2.2.5.

![bildschirmfoto 2017-07-26 um 10 09 44](https://user-images.githubusercontent.com/1425566/28611037-c2eab098-71ea-11e7-8341-89d63f141cbd.png)

I also removed Easy Themes and did a new installation via Contao Manager, but the Dom-Inject still doesn't work.

Details of my user settings:

![bildschirmfoto 2017-07-26 um 10 35 53](https://user-images.githubusercontent.com/1425566/28612063-4d2ceb1a-71ee-11e7-9a15-0055d004d369.png)

I have the same szenario on a second Contao installation and there Easy Themes works like a charm. Same constellation: All-Inkl as provider, Contao 4.4.2, Contao Manager Beta 10 and also Easy Themes 2.2.6:

![bildschirmfoto 2017-07-26 um 10 28 26](https://user-images.githubusercontent.com/1425566/28611786-381ea67e-71ed-11e7-8c17-101ff27dac64.png)

Details of my user settings here in the installation:

![bildschirmfoto 2017-07-26 um 10 36 54](https://user-images.githubusercontent.com/1425566/28612113-711261ea-71ee-11e7-81b6-778980b7b15b.png)

**Comment by jscholtysik** [comment]
Also an update to Contao 4.4.3 does not solve the problem...

**Comment by qzminski** [comment]
Hmm that's strange, I cannot reproduce the issue. Can you try creating a brand new user and checking if it works there? I suspect there may be some legacy data for that particular user record...

**Comment by jscholtysik** [comment]
A new user did have the same problem. I did now an update from Contao 4.4.3 to 4.4.7 and the problem resolved itself. Now the DOM-Inject works again.
