### ISSUE TITLE
Interner Titel für easy_themes & Aktivierung im Benutzerprofil schlagen fehl

### ISSUE THREAD

**Issue by Pellinger** [terminal42/contao-easy_themes#37]
Contao 4.4.3 (nackte Installation)
easy_themes 2.2.6
manager: 1.0 beta 10

Problem: 
Bei Vergabe eines internen Titels erscheint:
> An exception occurred while executing 'UPDATE tl_theme SET easy_themes_internalTitle='' WHERE id...

Beim Versuch easy_themes in den Benutzereinstellungen zu aktivieren, hängt sich das System mit dem Overlay "Die Daten werden geladen" auf.

**Comment by Toflar** [comment]
Hey Pelle, hast du denn das DB-Update laufen lassen? Das Feld müsste eigentlich da sein?

**Comment by Pellinger** [comment]
Hallo Yanick, ich hatte es in einer zweiten nackten Installation problemlos installieren können. DP Update, Cache etc alles gemacht. Reproduzieren konnte ich es in der zweiten nicht mehr: Hier mal der Eintrag aus dem Log_
>app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT tl_layout.*, j1.id AS pid__id, j1.tstamp AS pid__tstamp, j1.name AS pid__name, j1.author AS pid__author, j1.folders AS pid__folders, j1.screenshot AS pid__screenshot, j1.templates AS pid__templates, j1.vars AS pid__vars, j1.defaultImageDensities AS pid__defaultImageDensities, j1.easy_themes_internalTitle AS pid__easy_themes_internalTitle FROM tl_layout LEFT JOIN tl_theme j1 ON tl_layout.pid=j1.id WHERE tl_layout.id='2' LIMIT 0,1':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'j1.easy_themes_internalTitle' in 'field list' at /var/customers/webs/peltzer/supersonic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'j1.easy_themes_internalTitle' in 'field list' at xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'j1.easy_themes_internalTitle' in 'field list' at xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

**Comment by Toflar** [comment]
Jo, "unknown column in field list". Da war das DB Feld nicht vorhanden. Warum ist natürlich schwierig zu sagen jetzt aber eigentlich ist dafür ja das Install-Tool da :)
