### ISSUE TITLE
Easythemes Backend Module does not work in Contao 4.5.0

### ISSUE THREAD

**Issue by Seefahrer** [terminal42/contao-easy_themes#38]
I use Easythemes for a long time as Backend-Module in the Layout group. Everything was fine so far unless I updated to Contao 4.5.0.
In case I click onto one of the "Easythemes" menu items e.g. "Theme bearbeiten" or "Module" etc., Contao only opens the "Themes" menu located  above ... where I can choose the corresponding menu item from the icons at the right site. Contao does not longer switch directly to the edit mode chosen in Easythemes menu. Hope, I could make myself clear somehow?!

**Comment by Stefko** [comment]
I've installed ET via the ContaoManager to a new Contao 4.5 and whatever I adjust nothing happens in the left column.
I've also opened a thread at the ContaoForum -> https://community.contao.org/de/showthread.php?69245-EasyThemes-und-Contao4-5-klappt-hier-nicht

**Comment by HendrikBengs** [comment]
+1

**Comment by qzminski** [comment]
This is a Contao issue https://github.com/contao/core-bundle/issues/1357.

**Comment by Anke** [comment]
Just installed easy_themes on a new Contao 4.5 project. 

Selecting "backend module" sets the ET menu where I want it.
Selecting "DOM inject" places it left of the backend menu, pushing the #container to the right.
"Kontext menu" and "Mouseover" aren't working.
The styles, modules and layout links only open the themes setup.

Trying to change the ET options in my profile (via the backend header) leads to weird results like replacing my email address by my user name. Using the "users" menü to change my profile both activation date fields suddenly contain my user name, leading to errors when trying to save the changes.

**Comment by Toflar** [comment]
Yeah, it's a Contao bug that has just been reported yesterday and is not fixed yet.
