### ISSUE TITLE
Eeasy Themes as Backend Module still not working ...

### ISSUE THREAD

**Issue by Seefahrer** [terminal42/contao-easy_themes#39]
If one uses Easythemes as Backend-Module e.g. in the Layout group in Contao 4.5.4, clicking on any menu item simply jumps to "Layout - Themes". 

ET used on mouseover or context menu is working w/o problems.

**Comment by rflx** [comment]
I can confirm the problem mentioned above.
The ampersand encoding in the URL is wrong. Maybe you can fix it with `%26` or `[&]`?

**Comment by frontendschlampe** [comment]
I also confirm ... the url which want to open is:
```http://my.domain/contao?do=themes&amp;table=tl_layout&amp;id=1```
instead of
```http://my.domain/contao?do=themes&table=tl_layout&id=1```

**Comment by frontendschlampe** [comment]
with option "context menu" it's working
