### ISSUE TITLE
Runtime exception in constructor when called without request 

### ISSUE THREAD

**Issue by m-vo** [terminal42/contao-easy_themes#40]
These lines ...
https://github.com/terminal42/contao-easy_themes/blob/09c810cf451bdcf631d82378cb88299b9104e798/EasyThemes.php#L31-L35

.. are leading to an runtime exception if the request stack does not contain a request (in `Contao\User\loadUserByUsername`). This is for example the case when Contao's poor man cron job gets executed from the backend.

**Comment by qzminski** [comment]
This fix in ff328f9 should do. Can you give it a try?

**Comment by qzminski** [comment]
Ok the previous fix was wrong, the 251c743 should do.

**Comment by m-vo** [comment]
Thanks @qzminski - this will be fixed in Contao 4.5.8 though (see https://github.com/contao/core-bundle/issues/1458), so you might want to revert the changes once you are raising the requirements.
