### ISSUE TITLE
Anzeigefehler mit Contao 4.8

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-easy_themes#42]
Mit Contao 4.8 werden die Namen der verfügbaren Module nicht mehr korrekt angezeigt. Im Profil stehen irgendwie nur noch die Anfangsbuchstaben (wobei bei Module ein "F" steht statt einem "M")

<img width="1184" alt="Bildschirmfoto 2019-08-15 um 15 04 48" src="https://user-images.githubusercontent.com/1232819/63096415-2c2d8800-bf6e-11e9-92dd-4fa56316f796.png">

In der Navi dann natürlich das selbe.

**Comment by planepix** [comment]
Danke fürs reporten @frontendschlampe. Wollte das eben auch nach einem erfolgreichen Update auf 4.8.0 melden. Danke an euch für alles!

**Comment by phamilton4321** [comment]
@frontendschlampe F steht hier für Frontend-Module. Aber der Anzeige Fehler ist auch bei meiner 4.8.0 Installation

**Comment by Anke** [comment]
Bis C4.7 funktioniert es noch
