### ISSUE TITLE
Compile Error: Cannot declare class EasyThemesRunOnce, because the name is already in use

### ISSUE THREAD

**Issue by Mynyx** [terminal42/contao-easy_themes#43]
Nach dem Upgrade auf Contao 4.9 ist beim erstmaligen Aufruf des Installtools folgender Fehler aufgetreten:

> [2020-02-18 21:47:58] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_route":"contao_install","_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction"},"request_uri":"https://xxx/contao/install","method":"GET"} []
> [2020-02-18 21:47:58] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Cannot declare class EasyThemesRunOnce, because the name is already in use" at /www/htdocs/xxx/vendor/terminal42/contao-easy_themes/runonce/runonce.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Compile Error: Cannot declare class EasyThemesRunOnce, because the name is already in use at /www/htdocs/xxx/vendor/terminal42/contao-easy_themes/runonce/runonce.php:0)"} []

**Comment by operatorone** [comment]
Habe denselben Fehler in 4.9.13

**Comment by aschempp** [comment]
this will become obsolete in version 3 (see `main` branch)
