### ISSUE TITLE
Password changed after activating easy_themes

### ISSUE THREAD

**Issue by petrad** [terminal42/contao-easy_themes#47]
I installed Contao 4.10 and added a Contao backend user admin. After activating easy_themes in that profile, the password in the database changed to "*****". 
Thank you in advance for checking it out.
Petra

**Comment by richardhj** [comment]
Can you list all extensions of your Contao installation?

**Comment by petrad** [comment]
sure, no problem:

        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "4.10.*",
        "dklemmt/contao_dk_mmenu": "2.1",
        "do-while/contao-backupdb-bundle": "^1.4",
        "erdmannfreunde/euf_grid": "2.2",
        "erdmannfreunde/theme-toolbox": "^1.0",
        "jonnysp/cookieconsent": "^0.0.8",
        "madeyourday/contao-rocksolid-custom-elements": "^2.2",
        "terminal42/contao-easy_themes": "^2.2"

**Comment by richardhj** [comment]
Fixed in contao/contao#2385.
