### ISSUE TITLE
ET influences Download of files in unpublished foldes

### ISSUE THREAD

**Issue by eBlick** [terminal42/contao-easy_themes#49]
It seems that easy themes has influence on downloads in unpublished folders.

They do not work properly when easy themes is installed.
I have experienced these problems in multiple installations now and as soon as et is deinstalled the download works.

Environment:
php 7.4
Contao Version > 4.4.28 and 4.9 all Versions.

Perhaps it is worth checking as I have detected no other correlations as a cause.

**Comment by richardhj** [comment]
Can you specify the issue, i.e. the error message?

**Comment by eBlick** [comment]
Just a message "failed to download" in the browser.
I have just updated easy-themes from 2.2.8 to 2.2.11.
That solved the problem in on installation now.

**Comment by richardhj** [comment]
Great!
