### ISSUE TITLE
PHP 8.0.2 -> sprintf(): Argument #1 ($format) must be of type string, array given

### ISSUE THREAD

**Issue by jochi44** [terminal42/contao-easy_themes#50]
Can't access the Contao backend (V 4.11.0) after upgrading to php V8.0.2, error message:

`[2021-02-24T08:36:05.898081+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "sprintf(): Argument #1 ($format) must be of type string, array given" at /var/www/clients/clientXYZ/webXYZ/web/vendor/terminal42/contao-easy_themes/EasyThemes.php line 197 {"exception":"[object] (TypeError(code: 0): sprintf(): Argument #1 ($format) must be of type string, array given at /var/www/clients/clientXYZ/webXYZ/web/vendor/terminal42/contao-easy_themes/EasyThemes.php:197)"} []`

**Comment by aschempp** [comment]
see #51
