### ISSUE TITLE
update to 3.0 

### ISSUE THREAD

**Issue by magicsepp** [terminal42/contao-easy_themes#53]
After upgrading to 3.0 with contao 4.9.25 the backend comes with an Internal Server Error  "parse_str() expects parameter 1 to be string, null given"
log:
request.CRITICAL: Uncaught PHP Exception TypeError: "parse_str() expects parameter 1 to be string, null given" at D:\laragon4\www\cto44\vendor\terminal42\contao-easy_themes\src\Helper.php line 221 {"exception":"[object] (TypeError(code: 0): parse_str() expects parameter 1 to be string, null given at D:\\laragon4\\www\\cto44\\vendor\\terminal42\\contao-easy_themes\\src\\Helper.php:221)"} []

**Comment by aschempp** [comment]
thanks for the report. It should be fixed in version 3.0.1

**Comment by magicsepp** [comment]
Thanks Andreas for the fast fix, now it works.
