### ISSUE TITLE
Contao 4.9 and ArrayUtil

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-easy_themes#55]
The extension is currently unlocked for Contao 4.9. However it uses `Contao\ArrayUtil`, which is only available in Contao 4.10 and higher.

**Comment by rabauss** [comment]
Fixed with #67

**Comment by fritzmg** [comment]
That won't really fix it though. There needs to be a `3.1.2` release that fixes the original problem and then you can create a `3.1.3` release that uses `Contao\ArrayUtil` with the increased `contao/core-bundle` dependency.

**Comment by rabauss** [comment]
Yes, that's what I suggested with my PRs ;-)

**Comment by fritzmg** [comment]
Oh I see, yes, I missed that PR.

**Comment by rabauss** [comment]
fixed in [3.1.2](https://github.com/terminal42/contao-easy_themes/releases/tag/3.1.2)

thanks @Toflar
