### ISSUE TITLE
Undefined Variable, undefined Array - Fehler bei Hoster NetCup

### ISSUE THREAD

**Issue by tschero** [terminal42/contao-easy_themes#57]
Guten Tag Zusammen,

im Zusammenhang mit einem "composer update" wird beim Hoster NetCup die SESSION nicht aufgebaut und mehrere Fehler von "easyThemes" gemeldet.

1)
`Warning: Undefined global variable $TL_EASY_THEMES_MODULES in /httpdocs/contao_cms/vendor/terminal42/contao-easy_themes/config/config.php on line 65`

2)
`Warning: Undefined array key "do" in /httpdocs/contao_cms/vendor/terminal42/contao-easy_themes/config/config.php on line 78`

3)
`Warning: Undefined array key "do" in /httpdocs/contao_cms/vendor/terminal42/contao-easy_themes/config/config.php on line 80
09:47:46 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod --ansi". Message: "Failed to start the session because headers have already been sent by "/httpdocs/contao_cms/vendor/terminal42/contao-easy_themes/config/config.php" at line 65." ["exception" => RuntimeException { …},"command" => "cache:warmup --env=prod --ansi","message" => "Failed to start the session because headers have already been sent by "/httpdocs/contao_cms/vendor/terminal42/contao-easy_themes/config/config.php" at line 65."]
`

Hoster: NetCup Webhostimg 8000
PHP-Version: 8.1
Contao: 4.13.1

Wenn mehr Info´s benötigt werden, gerne melden.

Gruß
tschero

**Comment by Toflar** [comment]
Die Version wäre relevant. Nur v3 ist mit PHP 8 kompatibel.

**Comment by tschero** [comment]
Ist Version 2. Was genau muss dann in der composer.json stehen damit immer die neuste Version verwendet wird?
`"terminal42/contao-easy_themes": "^3.0"`
oder
`"terminal42/contao-easy_themes": "^3"`

**Comment by Toflar** [comment]
Beides geht.

**Comment by tschero** [comment]
Danke schön, der o.a. Fehler ist behoben.
Ein weiterer Fehler mit der Session bleibt jedoch bestehen.
`Warning: SessionHandler::read(): open(/var/lib/php/sessions/sess_47f10b812fcafe1c6e6c3b302647281b, O_RDWR) failed: No such file or directory (2) in /httpdocs/contao_cms/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 49

Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /httpdocs/contao_cms/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php on line 149
14:14:22 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod --ansi". Message: "Failed to start the session." ["exception" => RuntimeException { …},"command" => "cache:warmup --env=prod --ansi","message" => "Failed to start the session."]

In NativeSessionStorage.php line 150:

  Failed to start the session.


cache:warmup [--no-optional-warmers]

14:14:22 CRITICAL  [console] An error occurred while using the console. Message: "An error occurred while executing the "/usr/local/php81/bin/php -dmemory_limit=8G /httpdocs/contao_cms/vendor/contao/manager-bundle/bin/contao-console cache:warmup --env=prod --ansi" command: 14:14:22 CRITICAL  [console] Error thrown while running command "cache:warmup --env=prod --ansi". Message: "Failed to start the session." ["exception" => RuntimeException { …},"command" => "cache:warmup --env=prod --ansi","message" => "Failed to start the session."]

In NativeSessionStorage.php line 150:

  Failed to start the session.


cache:warmup [--no-optional-warmers]

" ["exception" => RuntimeException { …},"message" => """  An error occurred while executing the "/usr/local/php81/bin/php -dmemory_limit=8G /httpdocs/contao_cms/vendor/contao/manager-bundle/bin/contao-console cache:warmup --env=prod --ansi" command: 14:14:22 \e[31mCRITICAL \e[39m \e[33m[console]\e[39m Error thrown while running command "cache:warmup --env=prod --ansi". Message: "Failed to start the session." \e[0;38;5;208m[\e[m\e[0;38;5;208m"\e[38;5;113mexception\e[0;38;5;208m" => \e[38;5;38mRuntimeException\e[0;38;5;208m { …},\e[m\e[0;38;5;208m"\e[38;5;113mcommand\e[0;38;5;208m" => "\e[1;38;5;113mcache:warmup --env=prod --ansi\e[0;38;5;208m",\e[m\e[0;38;5;208m"\e[38;5;113mmessage\e[0;38;5;208m" => "\e[1;38;5;113mFailed to start the session.\e[0;38;5;208m"\e[m\e[0;38;5;208m]\e[m\n  \n  \e[33mIn NativeSessionStorage.php line 150:\e[39m\n  \e[37;41m                                \e[39;49m\n  \e[37;41m  Failed to start the session.  \e[39;49m\n  \e[37;41m                                \e[39;49m\n  \n  \e[32mcache:warmup [--no-optional-warmers]\e[39m\n  \n  """]

In ContaoSetupCommand.php line 120:

  An error occurred while executing the "/usr/local/php81/bin/php -dmemory_li
  mit=8G /httpdocs/contao_cms/vendor/contao/manager-bundle/bin/contao-console
   cache:warmup --env=prod --ansi" command: 14:14:22 CRITICAL
  m[console] Error thrown while running command "cache:warmup --env=prod
   --ansi". Message: "Failed to start the session." [
  ;208m"exception" => RuntimeException
  8;5;208m { …},"command" => "
  5;113mcache:warmup --env=prod --ansi","
  113mmessage" => "Failed to start the session.
  38;5;208m"]

  In NativeSessionStorage.php line 150:

    Failed to start the session.


  cache:warmup [--no-optional-warmers]


contao:setup

Script @php vendor/bin/contao-setup handling the post-update-cmd event returned with error code 1
`

Das liegt aber wahrscheinlich nicht an easyThemes.

Vielen Dank und Gruß

**Comment by tschero** [comment]
easythemes funktioniert jetzt im Backend nicht mehr wie gewohnt (DOM-inject).
Es wir links oben angezeigt(siehe Anhang
![easythemes](https://user-images.githubusercontent.com/7802635/159164432-0c8ff21b-a591-40fa-b97f-def70656bd26.jpg)
)
