### ISSUE TITLE
Version 3.1.1 not compatible with contao 4.9

### ISSUE THREAD

**Issue by salteax** [terminal42/contao-easy_themes#63]
Commit 461e60f breaks the compatibility with contao version 4.9. The cause of this seems to be the use of the method 'getDefaultTokenValue()' which only exists in contao versions that are more recent than version 4.9.

**Comment by Aybee** [comment]
Thank you, worked for me on 4.9.38 👍

**Comment by rabauss** [comment]
fixed in [3.1.2](https://github.com/terminal42/contao-easy_themes/releases/tag/3.1.2)
