### ISSUE TITLE
Anzeige verrutscht bei DOM-Inject und Layout geschlossen 

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-easy_themes#7]
wenn Layout geschlossen ist und DOM-inject angewählt ist, wird das "Baumstückchen" trotzdem eingefügt - dabei wird das Seitenlayout "zerschossen"

siehe Screenshot

Contao 3.1.5 + ET 2.0.4 stable  4
![zwischenablage01](https://f.cloud.github.com/assets/1045318/1634845/9855f9c0-57a2-11e3-853f-55c6646a0f59.jpg)

**Comment by Anke** [comment]
Hallo,

das beschriebene Verhalten habe ich auch in Contao 3.5.2 festgestellt, mit easy_themes 2.1.3, wobei ich die Kurzanzeige gewählt habe (also nur die Icons) und das flexible Contao-Backendtheme.

VG, Anke
